# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(default=None, max_length=150)),
                ('last_name', models.CharField(default=None, max_length=150)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='AdminWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Admin')),
            ],
            options={
                'db_table': 'admin_website',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default=None, max_length=150)),
            ],
            options={
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='WebsiteData',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('no_of_visitors', models.PositiveIntegerField(default=0)),
                ('total_usage_hours', models.PositiveIntegerField(default=0)),
                ('no_of_hits', models.PositiveIntegerField(default=0)),
                ('last_visited', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'website_data',
            },
        ),
        migrations.AddField(
            model_name='keywords',
            name='website_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WebsiteData'),
        ),
        migrations.AddField(
            model_name='adminwebsite',
            name='website_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WebsiteData'),
        ),
    ]
