# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedata',
            name='total_usage_hours',
            field=models.FloatField(default=0),
        ),
    ]
